### ISSUE TITLE
Contact form linked

### ISSUE THREAD

**Issue by Sapna2001** [Catalyst-CSE/OpenSourceEvents-Frontend#100]
## Description
Contact form linked in homepage, about page and team page navbar

### Update [Required]
- [ ] [Contact form linked]

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

**Comment by anubhavsingh16** [comment]
@Sapna2001 I cannot understand this issue?

**Comment by Sapna2001** [comment]
The contact form has been linked to the navbar as suggested by @aryamanpuri .
