### ISSUE TITLE
bottom to top button 

### ISSUE THREAD

**Issue by Amankumar29** [Catalyst-CSE/OpenSourceEvents-Frontend#103]
it will be good to have an hiding bottom to top button means when we go down then it will appear and while at the top of the website it will disappear or we can just add it above the footer in the right side.

![Screenshot (16)](https://user-images.githubusercontent.com/54955755/82856972-3d5bea00-9f2d-11ea-96ce-b8adf1b43ff7.png)

**Comment by Amankumar29** [comment]
@anubhavsingh16

**Comment by anubhavsingh16** [comment]
yes, @Amankumar29 these small effects makes wonder.

**Comment by Amankumar29** [comment]
@Sapna2001 i think you should work on this issue as it will help you to improve your skills.
