### ISSUE TITLE
Add website url

### ISSUE THREAD

**Issue by HeroicHitesh** [Catalyst-CSE/OpenSourceEvents-Frontend#58]
## Description
As a user/visitor/contributor,
I need to add the website link to the repo,
so that I can it can be easily accessible for someone who wants to see the end result not the codebase, and also, for those who want to contribute by looking into the project.
### Update [Required]
- [ ] Website link visible on the Github repo.
## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

**Comment by HeroicHitesh** [comment]
I would like to resolve this issue please comment your website URL here.

**Comment by aryamanpuri** [comment]
Thank you for opening this issue.
we have discussed to deploy it on netlfiy and would be deployed by tomorrow.
Anything you want to add in

**Comment by HeroicHitesh** [comment]
Nice. Just one thing mention the URL here after the deployment is done so that I can add it to the description.

**Comment by aryamanpuri** [comment]
okay, no problem.
I will add the link

**Comment by HeroicHitesh** [comment]
@aryamanpuri Any updates on deployment? If not yet deployed and you are busy can I help with the deployment part?

**Comment by HeroicHitesh** [comment]
Issue resolved in commit 6ddfc39e91014a360331e407f44460c933df58c2

**Comment by aryamanpuri** [comment]
Thanks for your contribution. 
You can also contribute to https://github.com/Catalyst-CSE/Catalyst
