### ISSUE TITLE
Adjust logo and contact us section below

### ISSUE THREAD

**Issue by anubhavsingh16** [Catalyst-CSE/OpenSourceEvents-Frontend#60]
## Description:
Logo and Contact section(join our newsletter) of footer adjust at the bottom at the same hight of the GitHub button. `And make hight of footer smaller.`

## Mocks
![issue](https://user-images.githubusercontent.com/47811606/82592416-7f4bff80-9bbe-11ea-835d-d97ee777d6c3.png)

### Update [Required]
- [x] [move logo bottom]
- [x] [move join our newsletter bottom]
- [x] [move scroll button right]
- [x] [hight of footer smaller so it look 10% of whole webpage]

## Definition of Done
- [x] All of the required items are completed.
- [x] Approval by 1 mentor.

**Comment by anubhavsingh16** [comment]
@vinayaksh42 can you solve this

**Comment by vinayaksh42** [comment]
![82592416-7f4bff80-9bbe-11ea-835d-d97ee777d6c3](https://user-images.githubusercontent.com/54861487/82673264-2f714500-9c5f-11ea-8fd5-5396bbbbea75.png)
sir do you want it like this?

**Comment by anubhavsingh16** [comment]
yes @vinayaksh42

**Comment by vinayaksh42** [comment]
![chrome_p6tpuH1l6m](https://user-images.githubusercontent.com/54861487/82676072-68abb400-9c63-11ea-8d27-60e4c97ffced.png)
