### ISSUE TITLE
Add navbar in Team page

### ISSUE THREAD

**Issue by anubhavsingh16** [Catalyst-CSE/OpenSourceEvents-Frontend#61]
## Description
The team page is not cleaned add navbar and proper indentation at top and bottom for quality look.

### Update [Required]
- [x] [Add navbar]
- [x] [Add padding at top and bottom]

## Definition of Done
- [x] All of the required items are completed.
- [x] Approval by 1 mentor.

**Comment by Sapna2001** [comment]
Can I work on this?

**Comment by anubhavsingh16** [comment]
Ok do it @Sapna2001
