### ISSUE TITLE
Add scroll button 

### ISSUE THREAD

**Issue by anubhavsingh16** [Catalyst-CSE/OpenSourceEvents-Frontend#62]
## Description
Add the scroll button in `month section` in the left and right side. And make them highlighted.

### Update [Required]
- [x] [Add scroll button in both side and make them highlighted]

## Definition of Done
- [x] All of the required items are completed.
- [x] Approval by 1 mentor.

**Comment by naveenk97** [comment]
Can I do it. I am a beginner in this

**Comment by anubhavsingh16** [comment]
Ok do it and please follow code style.

**Comment by khan-rehan** [comment]
can i do this?

**Comment by anubhavsingh16** [comment]
@khan-rehan Yes, please.
