### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by HeroicHitesh** [Catalyst-CSE/OpenSourceEvents-Frontend#63]
## Description
As a user/contributor,
I need to start contributing to the project and for that we need to make relevant changes in README.md, which currently sets remote to `https://github.com/anitab-org/powerup-iOS.git` which is an archived repo, please tell if this is the correct URL or do we need to set remote to `https://github.com/OpenSourceEvents-Frontend.git` 
so that I can update it accordingly.

## Mocks
<img width="1440" alt="Screenshot 2020-05-22 at 7 41 52 AM" src="https://user-images.githubusercontent.com/37622734/82624305-d3c39f00-9bff-11ea-950d-345aa4126a7d.png">

### Update [Required]
- [ ] remote URL update in README.md

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

**Comment by HeroicHitesh** [comment]
@anubhavsingh16 @aryamanpuri Please tell if update is needed so that I can proceed with other issues.

**Comment by anubhavsingh16** [comment]
Copy URL from the repo.

**Comment by HeroicHitesh** [comment]
Resolved in PR #70
