### ISSUE TITLE
Add your details in the team section.

### ISSUE THREAD

**Issue by Amankumar29** [Catalyst-CSE/OpenSourceEvents-Frontend#67]
all the contributors you can add your details in the team section.

**Comment by anubhavsingh16** [comment]
Anubhav Singh
- Github link - `https://github.com/anubhavsingh16`
- Linkdin- `https://www.linkedin.com/in/anubhav-singh-27512a167/`

Aryaman Puri 
- Github link - `https://github.com/aryamanpuri`
- Linkdin- `https://www.linkedin.com/in/aryamanpuri/`

Aashim Garg 
- Github link - `https://github.com/aashimgarg`
- Linkdin- `https://www.linkedin.com/in/aashim-garg-370104198/`

**Comment by Amankumar29** [comment]
@anubhavsingh16 can you add your photo in the assets file. :)

**Comment by HeroicHitesh** [comment]
@Amankumar29 have a look at PR #73
