### ISSUE TITLE
Home Page

### ISSUE THREAD

**Issue by Sapna2001** [Catalyst-CSE/OpenSourceEvents-Frontend#81]
## Description
The side image in homepage is overflowing and overriding the text. 

## Mocks

![issue 2](https://user-images.githubusercontent.com/56690856/82722741-f5e41c80-9ce6-11ea-80db-7a26a1128a08.png)

## Definition of Done
- [ ] Approval by 1 mentor.

**Comment by Amankumar29** [comment]
check it in firefox,is it working fine? @Sapna2001

**Comment by Sapna2001** [comment]
In firefox the image overflows but the text can be seen.

![issue](https://user-images.githubusercontent.com/56690856/82726996-48cccc80-9d05-11ea-8260-5743d8b886c7.png)

**Comment by Amankumar29** [comment]
is this change working for all browsers?

**Comment by Sapna2001** [comment]
Yes, when the height is changed to 660px it is working on Firefox, chrome, explorer, and edge.

**Comment by Amankumar29** [comment]
okay
