### ISSUE TITLE
Fill colours in month section

### ISSUE THREAD

**Issue by anubhavsingh16** [Catalyst-CSE/OpenSourceEvents-Frontend#91]
## Description
After adding the scroll button in the month column, try to fill decent colours in the month names.
And add link of the respective events in the boxes.

### Update [Required]
- [x] [Add scroll button]
- [x] [Add colours in month name]
- [x] [Add events links]
## Definition of Done
- [x] All of the required items are completed.
- [x] Approval by 1 mentor.

**Comment by khan-rehan** [comment]
i will do this

**Comment by anubhavsingh16** [comment]
@khan-rehan first complete #62
