### ISSUE TITLE
Update Readme

### ISSUE THREAD

**Issue by anubhavsingh16** [Catalyst-CSE/OpenSourceEvents-Frontend#92]
## Description
Update Screenshot of website. Try to cover the important points.

## Definition of Done
- [x] All of the required items are completed.
- [x] Approval by 1 mentor.

**Comment by aashimgarg** [comment]
> ## Description
> 
> Update Screenshot of website. Try to cover the important points.
> ## Definition of Done
> 
>     * [x]  All of the required items are completed.
> 
>     * [x]  Approval by 1 mentor.

why to have a screenshot of the readme?
