### ISSUE TITLE
changing the design of arrows.

### ISSUE THREAD

**Issue by Amankumar29** [Catalyst-CSE/OpenSourceEvents-Frontend#98]
## I think having only arrows will be fine.

![Screenshot (15)](https://user-images.githubusercontent.com/54955755/82815599-1a8eee80-9eb7-11ea-9322-741abb059f1b.png)

**Comment by Amankumar29** [comment]
your views? @anubhavsingh16

**Comment by anubhavsingh16** [comment]
I think current design is better 😊

**Comment by aashimgarg** [comment]
what are your thoughts @anubhavsingh16 @Amankumar29

**Comment by anubhavsingh16** [comment]
I think its nice no need to change.

**Comment by aashimgarg** [comment]
> I think its nice no need to change.

we can go for alignment

**Comment by Amankumar29** [comment]
We can just remove the circular outline @anubhavsingh16 @aashimgarg

**Comment by Sapna2001** [comment]
@anubhavsingh16 @aashimgarg @Amankumar29 should I remove the circular outline?

**Comment by Amankumar29** [comment]
Wait for @anubhavsingh16 comments.

**Comment by anubhavsingh16** [comment]
Yaar mujhe to aise he acha lg rha.

**Comment by Amankumar29** [comment]
To bas allignment sahi kar dete hai 
@anubhavsingh16

**Comment by anubhavsingh16** [comment]
Hmm @Amankumar29

**Comment by Amankumar29** [comment]
@Sapna2001 can you please solve the issue of alignment.

**Comment by Sapna2001** [comment]
@Amankumar29 did you mean that the scroll button should be fixed. As now it moves up and down while scrolling.

**Comment by Amankumar29** [comment]
No, just to make the arrow inside the circle little bit in center

**Comment by Sapna2001** [comment]
@Amankumar29 please check if this is fine
![buttons](https://user-images.githubusercontent.com/56690856/82874111-1d3f2180-9f53-11ea-9b89-8daf17629673.png)

**Comment by anubhavsingh16** [comment]
> @Amankumar29 please check if this is fine
> ![buttons](https://user-images.githubusercontent.com/56690856/82874111-1d3f2180-9f53-11ea-9b89-8daf17629673.png)

yes, this one is nice to send PR.
